BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "routes" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"route_slug"	TEXT NOT NULL,
	"workset_hash"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "fully_explored_universes" (
	"workset_hash"	TEXT NOT NULL UNIQUE,
	"travelable"	BOOLEAN NOT NULL
);
COMMIT;
